# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Crimsol
tagline:             'Placeholder'
description:         'Placeholder'
url:                 http://crimsoll.github.io
baseurl:             ''

# About/contact
author:
  name:              Matt Musgrave

# Custom vars
version:             1.0.0
