# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               crimsol
tagline:             'Security chat'
description:         'My thoughts on security'
url:                 http://crimsol.xyz
baseurl:             ''
paginate:            3
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Matt
  email:             crimsol7449@gmail.com

# Custom vars
version:             1.0.0
